
-- INSERT RAIZ
TRUNCATE TABLE DB_COMPILADORES.RAIZ;
INSERT INTO DB_COMPILADORES.RAIZ VALUES (1,'el',2);
INSERT INTO DB_COMPILADORES.RAIZ VALUES (2,'la',2);
INSERT INTO DB_COMPILADORES.RAIZ VALUES (3,'los',2);
INSERT INTO DB_COMPILADORES.RAIZ VALUES (4,'las',2);
INSERT INTO DB_COMPILADORES.RAIZ VALUES (5,'carr',3);
INSERT INTO DB_COMPILADORES.RAIZ VALUES (6,'coch',3);
INSERT INTO DB_COMPILADORES.RAIZ VALUES (7,'vehicul',3);
INSERT INTO DB_COMPILADORES.RAIZ VALUES (8,'llant',3);
INSERT INTO DB_COMPILADORES.RAIZ VALUES (9,'moto',3);
INSERT INTO DB_COMPILADORES.RAIZ VALUES (10,'radi',3);
INSERT INTO DB_COMPILADORES.RAIZ VALUES (11,'vi',3);
INSERT INTO DB_COMPILADORES.RAIZ VALUES (12,'carreterr',3);
INSERT INTO DB_COMPILADORES.RAIZ VALUES (13,'person',3);
INSERT INTO DB_COMPILADORES.RAIZ VALUES (14,'con',4);
INSERT INTO DB_COMPILADORES.RAIZ VALUES (15,'para',4);
INSERT INTO DB_COMPILADORES.RAIZ VALUES (16,'en',4);
INSERT INTO DB_COMPILADORES.RAIZ VALUES (17,'por',4);
INSERT INTO DB_COMPILADORES.RAIZ VALUES (18,'hasta',4);
INSERT INTO DB_COMPILADORES.RAIZ VALUES (19,'hacia',4);
INSERT INTO DB_COMPILADORES.RAIZ VALUES (20,'sobre',4);
INSERT INTO DB_COMPILADORES.RAIZ VALUES (21,'sin',4);
INSERT INTO DB_COMPILADORES.RAIZ VALUES (22,'manej',1);
INSERT INTO DB_COMPILADORES.RAIZ VALUES (23,'conduc',1);
INSERT INTO DB_COMPILADORES.RAIZ VALUES (24,'grand',1);
INSERT INTO DB_COMPILADORES.RAIZ VALUES (25,'moviliz',1);
INSERT INTO DB_COMPILADORES.RAIZ VALUES (26,'corr',1);
INSERT INTO DB_COMPILADORES.RAIZ VALUES (27,'bonit',1);
INSERT INTO DB_COMPILADORES.RAIZ VALUES (28,'conbustibl',3);


-- INSERT CLASIFICACION RAIZ
TRUNCATE TABLE DB_COMPILADORES.CLASIFICACION_RAIZ;
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(22,'a',3,1);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(22,'ar',3,1);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(22,'o',3,1);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(22,'ando',3,1);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(23,'e',3,1);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(1,'',1,1);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(2,'',2,1);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(3,'',1,2);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(4,'',2,2);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(5,'o',1,1);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(5,'os',1,2);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(6,'e',1,1);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(6,'es',1,2);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(7,'o',1,1);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(7,'os',1,2);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(8,'a',2,1);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(8,'as',2,2);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(9,'r',1,1);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(9,'res',1,2);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(10,'o',1,1);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(10,'os',1,2);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(11,'a',2,1);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(11,'as',2,2);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(12,'a',2,1);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(12,'as',1,2);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(24,'e',1,1);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(24,'es',1,2);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(13,'a',2,1);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(13,'as',2,2);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(25,'a',3,1);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(25,'an',3,2);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(26,'e',3,1);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(26,'en',3,2);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(27,'o',1,1);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(27,'os',1,2);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(14,'',3,3);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(15,'',3,3);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(16,'',3,3);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(17,'',3,3);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(18,'',3,3);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(19,'',3,3);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(20,'',3,3);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(21,'',3,3);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(28,'e',1,1);
INSERT INTO DB_COMPILADORES.CLASIFICACION_RAIZ VALUES(28,'es',1,2);

-- INSERT NATURALEZA
TRUNCATE TABLE DB_COMPILADORES.NATURALEZA;
INSERT INTO DB_COMPILADORES.NATURALEZA VALUES (1,'Verbo');
INSERT INTO DB_COMPILADORES.NATURALEZA VALUES (2,'Articulo');
INSERT INTO DB_COMPILADORES.NATURALEZA VALUES (3,'Sustantivo');
INSERT INTO DB_COMPILADORES.NATURALEZA VALUES (4,'Preposicion');

-- INSERT GENERO
TRUNCATE TABLE DB_COMPILADORES.GENERO;
INSERT INTO DB_COMPILADORES.GENERO VALUES (1,'Masculino');
INSERT INTO DB_COMPILADORES.GENERO VALUES (2,'Femenino');
INSERT INTO DB_COMPILADORES.GENERO VALUES (3,'Neutro');

-- INSERT NUMERO
TRUNCATE TABLE DB_COMPILADORES.NUMERO;
INSERT INTO DB_COMPILADORES.NUMERO VALUES (1,'Singular');
INSERT INTO DB_COMPILADORES.NUMERO VALUES (2,'Plural');
INSERT INTO DB_COMPILADORES.NUMERO VALUES (3,'Neutro');


COMMIT;



