
import java.awt.Color;
import java.util.Enumeration;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Administrador
 */
public class MainCompilador extends javax.swing.JFrame {

    /**
     * Creates new form MainCompilador
     */
    Lexico lexico = new Lexico();

    public MainCompilador() {
        try {
            if (isWindows()) {
                UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            } else {
                UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();
    }

    private boolean isWindows() {
        String os = System.getProperty("os.name").toLowerCase();
        return (os.indexOf("win") >= 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelCompilador = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaEntrada = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonPalabra = new javax.swing.JRadioButton();
        jRadioButtonOracion = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jRadioButtonPregunta = new javax.swing.JRadioButton();
        jPanelContracciones = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableContracciones = new javax.swing.JTable();
        jButtonConsultarContracciones = new javax.swing.JButton();
        BarraMenu = new javax.swing.JMenuBar();
        MenuAyuda = new javax.swing.JMenu();
        AcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextAreaEntrada.setColumns(20);
        jTextAreaEntrada.setRows(5);
        jScrollPane2.setViewportView(jTextAreaEntrada);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Modo Compilacion:");

        buttonGroup.add(jRadioButtonPalabra);
        jRadioButtonPalabra.setText("Palabra");
        jRadioButtonPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPalabraActionPerformed(evt);
            }
        });

        buttonGroup.add(jRadioButtonOracion);
        jRadioButtonOracion.setText("Oración");

        jButton1.setText("Compilar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup.add(jRadioButtonPregunta);
        jRadioButtonPregunta.setText("Pregunta");
        jRadioButtonPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPreguntaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonPalabra)
                .addGap(10, 10, 10)
                .addComponent(jRadioButtonOracion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonPregunta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonOracion)
                    .addComponent(jRadioButtonPalabra)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(jRadioButtonPregunta))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCompiladorLayout = new javax.swing.GroupLayout(jPanelCompilador);
        jPanelCompilador.setLayout(jPanelCompiladorLayout);
        jPanelCompiladorLayout.setHorizontalGroup(
            jPanelCompiladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCompiladorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCompiladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
        );
        jPanelCompiladorLayout.setVerticalGroup(
            jPanelCompiladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCompiladorLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Compilador", jPanelCompilador);

        jTableContracciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Contracción", "Resultado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableContracciones);

        jButtonConsultarContracciones.setText("Consultar");
        jButtonConsultarContracciones.setToolTipText("");
        jButtonConsultarContracciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarContraccionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelContraccionesLayout = new javax.swing.GroupLayout(jPanelContracciones);
        jPanelContracciones.setLayout(jPanelContraccionesLayout);
        jPanelContraccionesLayout.setHorizontalGroup(
            jPanelContraccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
            .addGroup(jPanelContraccionesLayout.createSequentialGroup()
                .addComponent(jButtonConsultarContracciones)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelContraccionesLayout.setVerticalGroup(
            jPanelContraccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContraccionesLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonConsultarContracciones)
                .addGap(0, 189, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Contracciones", jPanelContracciones);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        MenuAyuda.setText("Ayuda");

        AcercaDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        AcercaDe.setText("Acerca de Compilador");
        AcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcercaDeActionPerformed(evt);
            }
        });
        MenuAyuda.add(AcercaDe);

        BarraMenu.add(MenuAyuda);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultarContraccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarContraccionesActionPerformed

        lexico.cargarContracciones();

        String datos[] = new String[2];
        String Columnas[] = {"Contracción", "Resultado"};
        Enumeration a = lexico.listaContra();
        DefaultTableModel modelo = new DefaultTableModel(Columnas, 0);

        while (a.hasMoreElements()) {
            String llave = (String) a.nextElement();
            datos = lexico.Contraccion(llave).split(" ");
            modelo.addRow(datos);

            //System.err.println(lexico.Contraccion(llave));
        }
        //jTableContracciones.setModel(modelo);


        jTableContracciones.setModel(modelo);
        //jTableContracciones.setVisible(true);


    }//GEN-LAST:event_jButtonConsultarContraccionesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String cadena = jTextAreaEntrada.getText();
        cadena = cadena.toLowerCase();
        cadena = cadena.replaceAll("\n", " \n");
        cadena = cadena.replaceAll("\n", "");

        if (jRadioButtonPalabra.isSelected()) {
            if (!lexico.vocabulario(cadena)) {
                String arregloPalabras[] = lexico.arregloPalabras(cadena);
                String arregloEstadosPalabra[] = new String[arregloPalabras.length];
                for (int i = 0; i < arregloPalabras.length; i++) {
                    arregloEstadosPalabra[i] = lexico.arregloEstadosPalabra(arregloPalabras[i]);
                }
                lexico.cargarContracciones();
                if (!lexico.contraccion(arregloPalabras, arregloEstadosPalabra)) {

                    if (!lexico.validar(arregloPalabras)) {
                        lexico.composicionPalabra(arregloPalabras);
                        jTextArea2.setText(lexico.salida);
                        lexico.setSalida("");
                        jTextArea2.setForeground(Color.GREEN);
                    } else {
                        jTextArea2.setText(lexico.salida);
                        lexico.setSalida("");
                        jTextArea2.setForeground(Color.red);
                    }

                } else {
                    jTextArea2.setText(lexico.salida);
                    lexico.setSalida("");
                    jTextArea2.setForeground(Color.red);
                }


            } else {
                jTextArea2.setText(lexico.salida);
                lexico.setSalida("");
                jTextArea2.setForeground(Color.red);
            }
        } else if (jRadioButtonOracion.isSelected()) {
            if (!lexico.vocabulario(cadena)) {
                String arregloPalabras[] = lexico.arregloPalabras(cadena);
                String arregloEstadosPalabra[] = new String[arregloPalabras.length];
                for (int i = 0; i < arregloPalabras.length; i++) {
                    arregloEstadosPalabra[i] = lexico.arregloEstadosPalabra(arregloPalabras[i]);
                }
                lexico.cargarContracciones();
                if (!lexico.contraccion(arregloPalabras, arregloEstadosPalabra)) {

                    if (!lexico.validar(arregloPalabras)) {
                        //lexico.composicionPalabra(arregloPalabras);
                        //jTextArea2.setText(lexico.salida);
                        //lexico.setSalida("");
                        //jTextArea2.setForeground(Color.GREEN);
                        if (!lexico.composicionOracion(arregloPalabras)) {
                            jTextArea2.setText(lexico.salida);
                            lexico.setSalida("");
                            jTextArea2.setForeground(Color.GREEN);
                        } else {
                            jTextArea2.setText(lexico.salida);
                            lexico.setSalida("");
                            jTextArea2.setForeground(Color.red);
                        }

                    } else {
                        jTextArea2.setText(lexico.salida);
                        lexico.setSalida("");
                        jTextArea2.setForeground(Color.red);
                    }

                } else {
                    jTextArea2.setText(lexico.salida);
                    lexico.setSalida("");
                    jTextArea2.setForeground(Color.red);
                }


            } else {
                jTextArea2.setText(lexico.salida);
                lexico.setSalida("");
                jTextArea2.setForeground(Color.red);
            }
        } else if (jRadioButtonPregunta.isSelected()) {

            if (!lexico.vocabulario(cadena)) {
                String arregloPalabras[] = lexico.arregloPalabras(cadena);
                String arregloEstadosPalabra[] = new String[arregloPalabras.length];
                for (int i = 0; i < arregloPalabras.length; i++) {
                    arregloEstadosPalabra[i] = lexico.arregloEstadosPalabra(arregloPalabras[i]);
                }
                lexico.cargarContracciones();
                if (!lexico.pregunta(arregloPalabras)) {
                    jTextArea2.setText(lexico.salida);
                    lexico.setSalida("");
                    jTextArea2.setForeground(Color.GREEN);
                } else {
                    jTextArea2.setText(lexico.salida);
                    lexico.setSalida("");
                    jTextArea2.setForeground(Color.RED);
                }

            } else {
                jTextArea2.setText(lexico.salida);
                lexico.setSalida("");
                jTextArea2.setForeground(Color.red);
            }
        } else {
            jTextArea2.setText("Por favor seleccione un modo de compilación!!!");
            jTextArea2.setForeground(Color.red);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void AcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcercaDeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AcercaDeActionPerformed

    private void jRadioButtonPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPalabraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonPalabraActionPerformed

    private void jRadioButtonPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPreguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonPreguntaActionPerformed

    /**
     * @param args the command line arguments
     *
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainCompilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainCompilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainCompilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainCompilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainCompilador().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AcercaDe;
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JMenu MenuAyuda;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonConsultarContracciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCompilador;
    private javax.swing.JPanel jPanelContracciones;
    private javax.swing.JRadioButton jRadioButtonOracion;
    private javax.swing.JRadioButton jRadioButtonPalabra;
    private javax.swing.JRadioButton jRadioButtonPregunta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableContracciones;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextAreaEntrada;
    // End of variables declaration//GEN-END:variables
}
